name: wickedcurry
favicon: null
layout_spectrum: 0.055965324863791466
typography_spectrum: 0.5243236040696502
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.9729165437165648
  lightness: 0.7171009823214263
  saturation: 0.7496797060593963
  rhythmicContrast: 0.4552377359941602
purpose: []
